# Movie Ratings

[MovieLens](http://www.movielens.org/) is a website where users can submit ratings for movies that they watch and receive recommendations for movies. The collected data is made [publicly available for research](http://grouplens.org/datasets/movielens/).

We will be working with a data set of 1 million user ratings of movies. There are more recent data sets with more ratings, but these data sets do not contain demographic information about the users, which is perhaps the most interesting aspect of the data.

The MovieLens data is available at http://dlsun.github.io/pods/data/ml-1m/. The data consists of three files:

- `movies.dat`, which contains information about the movies, such as their title and their genre
- `ratings.dat`, which contains the 1 million ratings
- `users.dat`, which contains information about the users, such as their gender and their occupation

There is also a [README file](http://dlsun.github.io/pods/data/ml-1m/README.txt). You should skim this README file before starting the assignment. In particular, the data files do not have a header row, so you will need this README file to figure out what each column represents.

The code below reads in the `ratings.dat` dataset.

In [ ]:
import pandas as pd

data_dir = "https://dlsun.github.io/pods/data/ml-1m/"
columns = "UserID::MovieID::Rating::Timestamp".split("::")
ratings = pd.read_table(data_dir + "/ratings.dat",
                        sep="::", engine="python", encoding="ISO-8859-1",
                        header=None, names=columns)
ratings

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [ ]:
columns = "MovieID::Title::Genres".split("::")
movies = pd.read_table(data_dir + "/movies.dat",
                        sep="::", engine="python", encoding="ISO-8859-1",
                        header=None, names=columns)
movies

,MovieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [ ]:
columns = "UserID::Gender::Age::Occupation::Zip-code".split("::")

users = pd.read_table(data_dir + "/users.dat",
                        sep="::", engine="python", encoding="ISO-8859-1",
                        header=None, names=columns)
users

      UserID Gender  Age  Occupation Zip-code
0          1      F    1          10    48067
1          2      M   56          16    70072
2          3      M   25          15    55117
3          4      M   45           7    02460
4          5      M   25          20    55455
...      ...    ...  ...         ...      ...
6035    6036      F   25          15    32603
6036    6037      F   45           1    76006
6037    6038      F   56           1    14706
6038    6039      F   45           0    01060
6039    6040      M   25           6    11106

[6040 rows x 5 columns]

To answer each question, you will need to join 2 (or possibly even all 3) of the data sets to each other. Try to avoid joining more than you need to.

## Question 1

Some movies have been rated more times than others. Calculate the number of ratings for each movie, and make a visualization showing the distribution of the number of ratings.

_Hint:_ Some movies in `movies.dat` have been rated 0 times.

In [ ]:
# YOUR CODE HERE

_EXPLAIN YOUR APPROACH HERE. IN PARTICULAR, MENTION:_

- the relationships between the tables in your join (one-to-one, many-to-one, or many-to-many)
- the type of join you used (inner, outer, right, or left)
- what are the primary and foreign keys in the join?

## Question 2

What is the relationship between the age of the reviewer and ratings, if any?

In [ ]:
# YOUR CODE HERE

_EXPLAIN YOUR APPROACH AND YOUR CONCLUSION HERE. IN PARTICULAR, MENTION:_

- the relationships between the tables in your join (one-to-one, many-to-one, or many-to-many)
- the type of join you used (inner, outer, right, or left)
- what are the primary and foreign keys in the join?

## Question 3

Some movies are more popular among women than men (sometimes called "chick flicks"), while others are the opposite. Come up with a reasonable way to define how gender-skewed a movie by using its user ratings. Use your definition to determine the most gender-skewed movies.

In [ ]:
# YOUR CODE HERE

_EXPLAIN YOUR APPROACH AND YOUR CONCLUSION HERE. IN PARTICULAR, MENTION:_

- the relationships between the tables in your join (one-to-one, many-to-one, or many-to-many)
- the type of join you used (inner, outer, right, or left)
- what are the primary and foreign keys in the join?